title: Open Science Company Manifesto
author: TailorDev
description: >
  This manifesto aims at defining fundamental statements every Company running
  with the Open Science initiative in mind must respect and promote.
baseurl: ""
url: "http://manifesto.tailordev.fr"
